#!/usr/bin/env python

import rospy
from std_msgs.msg import String

global press_key
press_key = "0"

def callback(msg):

    global press_key
    press_key = msg.data

if __name__ == '__main__':

    rospy.init_node("testKeyboard")

    rospy.Subscriber("/keys", String, callback)

    # Loop rate (in Hz)
    rate = rospy.Rate(10)
    # Continuous execution loop
    while not rospy.is_shutdown():
        # Show the axes and buttons
        print 'keys:', press_key
        # Wait for the next iteration
        rate.sleep()